FROM docker.m.daocloud.io/ubuntu:22.04

ENV https_proxy=http://192.168.1.202:8889
ENV http_proxy=http://192.168.1.202:8889

ENV DEBIAN_FRONTEND=noninteractive
ENV CMAKE_VERSION="v3.28.5"
ENV CMAKE_TAR="cmake-3.28.5-linux-aarch64.tar.gz"
ENV CCACHE_DIR="ccache-4.9.1"
ENV CCACHE_SRC_TAR="v4.9.1.tar.gz"
ENV BFLOAT16_WHL="bfloat16-1.4.0-cp311-cp311-linux_aarch64.whl"

RUN sed -i 's@http://archive.ubuntu.com@http://mirrors.aliyun.com@g' /etc/apt/sources.list && \
    sed -i 's@http://ports.ubuntu.com@http://mirrors.aliyun.com@g' /etc/apt/sources.list && \
    sed -i 's@http://security.ubuntu.com@http://mirrors.aliyun.com@g' /etc/apt/sources.list


RUN apt update \
    && apt install -y ca-certificates apt-transport-https software-properties-common lsb-release \
    && apt install -y --no-install-recommends wget curl git make gfortran gcc g++ swig libssl-dev \
    && apt install -y gcc-12 g++-12 \
    && apt install -y python3.11 python3.11-dev python3.11-distutils \
    && apt install -y python3-setuptools \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 120 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 110 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 120 \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 310 \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 311 \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3 \
    && export PATH=$PATH:$HOME/.local/bin \
    && pip3 install wheel \
    && apt remove --purge -y \
    && rm -rf /var/lib/apt/lists/*

# install cmake, ccache and bfloat16
RUN cd /tmp \
    && wget https://github.com/Kitware/CMake/releases/download/${CMAKE_VERSION}/${CMAKE_TAR} \
    && tar --strip-components=1 -xz -C /usr/local -f ${CMAKE_TAR} \
    && rm -f ${CMAKE_TAR} \
    && wget https://github.com/ccache/ccache/archive/refs/tags/${CCACHE_SRC_TAR} \
    && tar xvfz ${CCACHE_SRC_TAR} \
    && cd ${CCACHE_DIR} \
    && mkdir build && cd build \
    && cmake -D CMAKE_BUILD_TYPE=Release .. \
    && make -j3 && make install \
    && cd ../.. && rm -rf ${CCACHE_DIR} ${CCACHE_SRC_TAR} \
    && wget https://github.com/zilliztech/knowhere/releases/download/v2.3.1/${BFLOAT16_WHL} \
    && pip3 install ${BFLOAT16_WHL} \
    && rm -f ${BFLOAT16_WHL}

# install knowhere dependancies
RUN apt update \
    && apt install -y libopenblas-openmp-dev libcurl4-openssl-dev libaio-dev libevent-dev lcov \
    && pip3 install conan==1.61.0 \
    && conan remote add default-conan-local https://milvus01.jfrog.io/artifactory/api/conan/default-conan-local

#RUN  apt install -y liburing-dev 

#COPY knowhere /knowhere
#RUN cd knowhere \
#    && mkdir -p build && cd build \
#    && conan install .. --build=missing -o with_ut=True -o with_diskann=True -o with_odinann=True -s compiler.libcxx=libstdc++11 -s build_type=Release \
    #&& conan build .. \
    #&& cd ../.. && rm -rf knowhere


#docker build -f knowhere/ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile -t knowhere-builder .
# docker run -it  --name knowhere-debug \
 # -v ~/wy/knowhere:/knowhere \
 # knowhere-builder \
 # /bin/bash
  
 # docker start/stop knowhere-debug
  

  
#4.手动执行前面dockerfile编译命令
 # docker exec -it knowhere-debug bash
 #cd knowhere 
 # mkdir -p build && cd build 
  
  
 #conan install .. --build=missing -o with_ut=True -o with_diskann=True -o with_odinann=True -s compiler.libcxx=libstdc++11 -s build_type=Release 
 
 #   conan build .. 
